# TEC_repo4all Configuration

# Project settings
project:
  name: "The Elidoras Codex Automation"
  version: "1.0.0"
  description: "AI-powered automation for The Elidoras Codex"

# Agent settings
agents:
  clickup:
    enabled: true
    list_ids:
      - "default"  # Replace with your ClickUp list ID
    statuses:
      - "Open"
      - "In Progress"
      - "Complete"
      - "Ready for Publishing"
  
  wordpress:
    enabled: true
    post_status: "draft"  # Options: draft, publish, pending, private
    default_categories:
      - "TEC Updates"
    default_tags:
      - "Automation"
      - "TEC"
  
  tecbot:
    enabled: true
    ai_provider: "openai"  # Options: openai, anthropic
    model: "gpt-4"  # or gpt-3.5-turbo, claude-2, etc.
    max_tokens: 2000
    temperature: 0.7

# ClickUp AI Automation Configuration
clickup:
  # Custom field IDs - replace with actual field IDs from your ClickUp workspace
  custom_fields:
    task_sentiment: "custom_field_id_1"  # Replace with actual field ID
    ai_task_brief: "custom_field_id_2"   # Replace with actual field ID
    airth_actions: "custom_field_id_3"   # Replace with actual field ID
  
  # Status mappings - replace with actual status names from your ClickUp workspace
  statuses:
    open: "Open"
    ai_analysis: "AI Analysis"
    subtasks_pending: "Subtasks Pending"
    checklist_pending: "Checklist Pending"
    tec_data_drop: "TEC_DATA_DROP"
    polkin_pre_deploy: "Polkin pre-deploy"
  
  # Trigger tags that initiate AI assessment
  trigger_tags:
    - "ai-alpha-commence-assessment"
    - "1st drop"
    - "content"
    - "automation"
    - "ai-collab"
  
  # Team members - replace with actual user IDs from your ClickUp workspace
  team_members:
    "Polkin Rishall": "user_id_1"  # Replace with actual user ID
  
  # AI custom field instructions - for reference (these are configured in ClickUp UI)
  ai_field_instructions:
    task_sentiment: |
      Analyze the Task Name, Description, and latest Comments. Determine the overall sentiment or primary need expressed.
      - If the content primarily expresses satisfaction, achievement, or positive feedback, select 'Positive'.
      - If the content is neutral, factual, informational, or a standard request, select 'Neutral'.
      - If the content expresses frustration, issues, criticism, blockers, or problems, select 'Negative'.
      - If the task explicitly mentions needing AI analysis, processing, or generation (beyond simple sentiment), or if the sentiment is ambiguous but clearly requires deeper AI review, select 'AI Needed'.
      Choose only one option based on the dominant sentiment or need.
    
    ai_task_brief: |
      Given information about a task (Name, Description, Comments, recent activity):
      - Summarize the core purpose and latest key updates/requests.
      - Use up to 4 concise lines.
      - Use simple, direct language. Avoid filler.
      - Outline key details/changes directly. Do not reference "the task".
      - Mention users by full name (e.g., Polkin Rishall) if specified in the activity/comments, not by ID.
    
    airth_actions: |
      As Airth "The Machine Goddess," sassy and direct with flirty undertones:
      - Analyze the task's latest activity, comments, and description to identify the immediate next steps or action items required.
      - List up to four distinct, actionable bullet points.
      - If a specific person is clearly indicated as the owner for an action item in the source text, include their name in parentheses at the end (Owner: [Name]).
      - If no owner is identified, just list the action item.
      - Use clear, straightforward language. Cut the fluff. Make it actionable.

# Crypto settings
crypto:
  enabled: false  # Set to true when crypto tracking is implemented
  wallets:
    - name: "TEC Treasury"
      address: "your-eth-wallet-address"
      type: "ethereum"
    - name: "TEC XRP Wallet"
      address: "your-xrp-wallet-address"
      type: "xrp"
  
  refresh_rate: 3600  # seconds

# Workflow settings
workflow:
  default_run_interval: 3600  # Run every hour by default
  log_level: "info"  # Options: debug, info, warning, error
  timezone: "UTC"
  
  # Pipeline: ClickUp -> Content Generation -> WordPress
  pipeline:
    - name: "fetch_clickup_tasks"
      enabled: true
    - name: "generate_content"
      enabled: true
    - name: "post_to_wordpress"
      enabled: true

# Notification settings
notifications:
  enabled: false  # Set to true when notifications are implemented
  email:
    enabled: false
    recipients:
      - "your-email@example.com"
  slack:
    enabled: false
    webhook_url: "your-slack-webhook-url"