name: TEC Automation Pipeline

on:
  schedule:
    # Runs every day at 1:00 AM UTC
    - cron: '0 1 * * *'
  workflow_dispatch:
    # Manual trigger from GitHub UI

jobs:
  run-automation:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run TEC automation pipeline
        run: python scripts/run_automation.py
        env:
          # ClickUp credentials
          CLICKUP_API_TOKEN: ${{ secrets.CLICKUP_API_TOKEN }}
          CLICKUP_LIST_ID: ${{ secrets.CLICKUP_LIST_ID }}
          
          # WordPress credentials
          WP_SITE_URL: ${{ secrets.WP_SITE_URL }}
          WP_USER: ${{ secrets.WP_USER }}
          WP_APP_PASS: ${{ secrets.WP_APP_PASSWORD }}
          
          # OpenAI API
          OPENAI_API_KEY: ${{ secrets.OPENAI_API }}
          
          # Blockchain APIs
          BLOCKFROST_KEY: ${{ secrets.BLOCKFROST_KEY }}
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
          XRPSCAN_API_KEY: ${{ secrets.XRPSCAN_API_KEY }}
          
          # Email settings
          EMAIL_SMTP_HOST: ${{ secrets.EMAIL_SMTP_HOST }}
          EMAIL_SMTP_PORT: ${{ secrets.EMAIL_SMTP_PORT }}
          EMAIL_SMTP_USER: ${{ secrets.EMAIL_SMTP_USER }}
          EMAIL_SMTP_PASS: ${{ secrets.EMAIL_SMTP_PASS }}
          
          # GCP credentials
          GCP_BUCKET_NAME: ${{ secrets.GCP_BUCKET_NAME }}
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      
      - name: Upload logs
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: automation-logs
          path: scripts/automation_*.log